version: "3.8"
services:
  web:
    build: tools/docker/nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/code
      - ./tools/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    user: '${USER_ID}:${GROUP_ID}'
    restart: unless-stopped
    build: tools/docker/php
    volumes:
      - ./:/code

  node:
    image: node:14-alpine
    user: '${USER_ID}:${GROUP_ID}'
    command: npm run build
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
