version: "3.8"
services:
  php:
    build:
      context: ./tools/docker/php-dev

  node:
    restart: unless-stopped
    image: node:14-alpine
    user: '${USER_ID}:${GROUP_ID}'
    command: npm run start:dev
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
